name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: journal
          root_file: main.tex
      - name: Commit report
        run: |
          git config --global user.name 'Hugo Simon'
          git config --global user.email 'hsimonfroy@users.noreply.github.com'
          git add main.pdf
          git commit -am "Automated report"
          git push
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: main.pdf
