name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: LaTeX compilation
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: journal
          root_file: main.tex
          
